### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by beneyal** [robertostling/eflomal#2]
I'm trying to run `eflomal`, but keep getting the following error:

```
Traceback (most recent call last):
  File "./align.py", line 142, in <module>
    if __name__ == '__main__': main()
  File "./align.py", line 136, in main
    use_gdb=args.debug)
  File "python/eflomal/eflomal.pyx", line 152, in eflomal.align
    subprocess.call(args)
  File "/home/bene/anaconda3/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/bene/anaconda3/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/home/bene/anaconda3/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'eflomal'
```

I tried running both `eflomal` and `align.py`, from both the `eflomal` directory and outside it. Am I doing something wrong?

**Comment by robertostling** [comment]
Did you compile and install both the `eflomal` executable and the Python bindings, as specified in the README?

**Comment by beneyal** [comment]
Sure did. I have the `eflomal` executable, and I can `import eflomal` in Python.

**Comment by robertostling** [comment]
The code expected the `eflomal` executable to be in `$PATH`, but I realize this might be inconvenient. I just pushed 8c8f5c2, which changes this to look in the same directory as `sys.argv[0]`. I hope this helps.

**Comment by beneyal** [comment]
Thanks! The error is gone, but I'm still not getting alignments. Doesn't seem there is an error in the output below, but `foo` is a file with 500 newline characters. Could it be because my target file is in Hebrew?

```
Aligning 500 sentences...
/home/datasets/srl/tools/aligners/eflomal/eflomal -m 3 -s /tmp/tmpzxt5uslb -t /tmp/tmpf6o8rw37 -n 3 -N 0.2 -1 56 -2 56 -3 224 -f foo
Read texts (500 sentences): 0.001 s
Vocabulary sizes are 1 (source), 1164 (target)
Created alignment structures: 0.000 s
Randomized alignment: 0.001 s
Aligning with model 1 (56 iterations)
Done: 0.003 s
Aligning with model 2 (56 iterations)
Done: 0.001 s
Aligning with model 3 (224 iterations)
Done: 0.004 s
Final argmax iteration: 0.000 s
Writing alignments to foo
```

**Comment by robertostling** [comment]
It says the vocabulary size is 1 for the source file, so you should double check that to make sure it is in the correct format. Hebrew should be no problem, any UTF-8 encoded text with some kind of word segmentation ought to work.

**Comment by beneyal** [comment]
Indeed, the problem was bad formatting. I only had a one-sentence-per-line file, and haven't noticed I should surround the sentences with `s` tags. It seems to work now.

**Comment by robertostling** [comment]
You don't have to add any tags, just make sure the file contains one sentence per line with space-separated words. Some of the example files (taken from the WPT shared task data) include sentence-ID tags because that's in their annotation format.
